# AUTO-GENERATED by generate_banner_art.py — do not hand-edit, regenerate instead
typeset -a SR_SUNBURST
SR_SUNBURST=(
  '                    .    ·    ⟡    ·    .                     '
  '                       \      |      /                        '
  '                    ·    \    |    /    ·                     '
  '                     ──────   ◈   ──────                      '
  '                    ·    /    |    \    ·                     '
  '                       /      |      \                        '
  '                    .    ·    ⟡    ·    .                     '
)

SR_RULE='            ═════════════════════════════════════             '
SR_TITLE='                 T H E   S P I C E   R O A D                  '
SR_TITLE_RAW='T H E   S P I C E   R O A D'
SR_TITLE_LPAD=17
SR_TITLE_RPAD=18
typeset -a SR_WAVES
SR_WAVES=(
  '    ∿∿∿∿∿∿  ≈≈≈≈≈≈≈≈≈  ∿∿∿∿∿∿∿  ≈≈≈≈≈  ∿∿∿∿∿∿∿∿∿  ≈≈≈≈≈≈≈     '
  '      ≈≈≈≈≈∿∿∿∿∿∿∿≈≈≈≈≈≈≈≈∿∿∿∿∿≈≈≈≈≈≈≈≈∿∿∿∿∿∿≈≈≈≈≈≈∿∿∿∿∿      '
)

SR_DIVIDER='──────────────────────────────────────────────────────────────'
