"""
Spice Road — banner art generator.
Produces banner-art.zsh, a data-only include file consumed by
welcome-banner.zsh. Keeping generation separate from the logic that colors
and animates it means the art can be re-centered, widened, or restyled
without ever hand-editing spaced-out Unicode strings.

Usage: python3 generate_banner_art.py > banner-art.zsh
"""

TOTAL_WIDTH = 62


def center(line):
    pad = TOTAL_WIDTH - len(line)
    left = pad // 2
    right = pad - left
    return " " * left + line + " " * right


SUNBURST = [
    ".    \u00b7    \u27e1    \u00b7    .",
    "\\      |      /",
    "\u00b7    \\    |    /    \u00b7",
    "\u2500\u2500\u2500\u2500\u2500\u2500   \u25c8   \u2500\u2500\u2500\u2500\u2500\u2500",
    "\u00b7    /    |    \\    \u00b7",
    "/      |      \\",
    ".    \u00b7    \u27e1    \u00b7    .",
]
TITLE = "T H E   S P I C E   R O A D"
RULE = "\u2550" * (len(TITLE) + 10)
WAVE1 = ("\u223f\u223f\u223f\u223f\u223f\u223f  \u2248\u2248\u2248\u2248\u2248\u2248\u2248\u2248\u2248  \u223f\u223f\u223f\u223f\u223f\u223f\u223f  "
         "\u2248\u2248\u2248\u2248\u2248  \u223f\u223f\u223f\u223f\u223f\u223f\u223f\u223f\u223f  \u2248\u2248\u2248\u2248\u2248\u2248\u2248")
WAVE2 = ("\u2248\u2248\u2248\u2248\u2248\u223f\u223f\u223f\u223f\u223f\u223f\u223f\u2248\u2248\u2248\u2248\u2248\u2248\u2248\u2248\u223f\u223f\u223f\u223f\u223f"
         "\u2248\u2248\u2248\u2248\u2248\u2248\u2248\u2248\u223f\u223f\u223f\u223f\u223f\u223f\u2248\u2248\u2248\u2248\u2248\u2248\u223f\u223f\u223f\u223f\u223f")


def sq(s):
    assert "'" not in s, "single quotes in art strings need the shell quoting rule revisited"
    return f"'{s}'"


def zsh_array(name, items):
    print(f"typeset -a {name}")
    print(f"{name}=(")
    for it in items:
        print(f"  {sq(it)}")
    print(")")
    print()


def main():
    print("# AUTO-GENERATED by generate_banner_art.py — do not hand-edit, regenerate instead")
    zsh_array("SR_SUNBURST", [center(l) for l in SUNBURST])
    print(f"SR_RULE={sq(center(RULE))}")
    print(f"SR_TITLE={sq(center(TITLE))}")

    title_centered = center(TITLE)
    lpad = len(title_centered) - len(title_centered.lstrip(" "))
    rpad = len(title_centered) - len(title_centered.rstrip(" "))
    print(f"SR_TITLE_RAW={sq(TITLE)}")
    print(f"SR_TITLE_LPAD={lpad}")
    print(f"SR_TITLE_RPAD={rpad}")

    zsh_array("SR_WAVES", [center(WAVE1), center(WAVE2)])
    print(f"SR_DIVIDER={sq('\u2500' * TOTAL_WIDTH)}")


if __name__ == "__main__":
    main()
